name = "openfort-shield-recovery-endpoint"
main = "src/index.ts"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "*/api/shield-session", custom_domain = true }
]

[vars]
# Values are set in the Deploy UI / dashboard
SHIELD_PUBLISHABLE_KEY = ""
SHIELD_SECRET_KEY = ""
SHIELD_ENCRYPTION_SHARE = ""
